src/app/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'app'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('greek_food/', include('greek_food.urls'), name='index')
]

src/greek_food/urls.py
from django.urls import path

from . import views

app_name = 'greek_food'

urlpatterns = [
    path('list', views.TableListView.as_view(), name='list'),
    path('reserved/<int:pk>', views.ReservedView.as_view(), name='reserved'),
]

src/greek_food/models.py
from django.db import models

from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone, dateformat



# Create your models here.


class Cafe(models.Model):
    name = models.CharField(max_length=64)


class CafePlaces(models.Model):
    cafe = models.ForeignKey(to=Cafe, related_name='cafe_places', on_delete=models.CASCADE)
    width = models.PositiveIntegerField(default=0)
    height = models.PositiveIntegerField(default=0)

    @property
    def square(self):
        return self.width * self.height


class TableInfo(models.Model):
    MAX_LIMIT = 100
    width = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                         MaxValueValidator(MAX_LIMIT)], default=0)
    height = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                          MaxValueValidator(MAX_LIMIT)], default=0)
    x = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                     MaxValueValidator(MAX_LIMIT)], default=0)
    y = models.PositiveSmallIntegerField(validators=[MinValueValidator(1),
                                                     MaxValueValidator(MAX_LIMIT)], default=0)

    def right(self):
        return self.x + self.width

    def bottom(self):
        return self.y + self.height

    def square(self):
        return self.right() * self.bottom()


class Table(TableInfo):
    SHAPE_CHOICES = (
        ("rectangular", 'Rectangular'),
        ("oval", 'Oval'),
    )
    place = models.ForeignKey(to=CafePlaces, related_name='tables', on_delete=models.CASCADE, default=0)
    number = models.PositiveSmallIntegerField()
    number_of_seats = models.PositiveSmallIntegerField(default=0)
    shape = models.CharField(choices=SHAPE_CHOICES, max_length=64)

    is_reserved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.number} - {self.shape}'

    def is_reserve(self, current_date):
        is_exists = self.orders.filter(start_date__lte=current_date, end_date__gte=current_date).exists()
        self.is_reserved = True if is_exists else False
        self.save()


class Customer(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField(max_length=254)


class Order(models.Model):
    customer = models.ForeignKey(to=Customer, related_name='orders', on_delete=models.CASCADE)


class OrderDetail(models.Model):
    order = models.ForeignKey(to=Order, related_name='order_details', on_delete=models.CASCADE)
    table = models.ForeignKey(to=Table, related_name='order_details', on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now=False)
    end_date = models.DateTimeField(auto_now=False)

src/greek_food/forms.py
from django.forms import Form, fields
from django.views.generic import FormView
from django import forms
from django.forms import ModelForm
from greek_food.models import Table, Order, Customer, OrderDetail

from datetimewidget.widgets import DateTimeWidget

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'


class OrderForm(ModelForm):
    name = forms.CharField(label=("Name", ))
    email = forms.EmailField(label=("E-mail",))
    class Meta:
        model = OrderDetail
        fields = ['name', 'email', 'start_date', 'end_date']
        widgets = {
            'start_date': forms.DateInput(format=('%m/%d/%Y'),
                                             attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                    'type': 'date'}),
            'end_date': forms.DateInput(format=('%m/%d/%Y'),
                                          attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                 'type': 'date'}),
        }


class DateForm(forms.Form):
    date = forms.DateTimeField(
        input_formats=['%d/%m/%Y %H:%M'],
        widget=forms.DateTimeInput(attrs={
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1'
        })
    )

src/greek_food/views.py
from datetime import timezone

from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.urls import reverse, reverse_lazy

# Create your views here.
from greek_food.models import Table, Order, Customer, OrderDetail
from greek_food.forms import OrderForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView, FormView

from django.http import HttpResponse, Http404

import datetime

from app import settings
from greek_food.forms import DateForm


class TableListView(ListView):
    model = Table
    template_name = 'greek_food/table_list.html'
    context_object_name = 'table_list'

    def get_queryset(self):
        date = self.request.GET.get('date')
        qs = super().get_queryset()

        if date:
            datetime_object = datetime.datetime.strptime(date, '%d/%m/%Y %H:%M')
            for i in qs:
                i.is_reserve(datetime_object)
        return qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=None, **kwargs)
        context['form'] = DateForm()
        context['title'] = 'LeaderBoard'
        return context


class ReservedView(CreateView):
    model = OrderDetail
    template_name = 'greek_food/reserved.html'
    extra_context = {'title': 'Send us a message!'}
    success_url = reverse_lazy('greek_food:list')
    form_class = OrderForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        table_id = self.kwargs.get(self.pk_url_kwarg)

        if form.is_valid():
            customer = Customer.objects.create(name=form.cleaned_data['name'], email=form.cleaned_data['email'])
            table = Table.objects.get(pk=table_id)
            order = Order.objects.get(customer=customer)
            self.object = form.save(commit=False)
            self.object.order = order
            self.object.table = table
            self.object.save()

            send_mail(
                 subject=f"Столик # {table_id} заказан",
                 message=f"Заказ успешен от {self.object.start_date} до {self.object.end_date}",
                 from_email=settings.EMAIL_HOST_USER,
                 recipient_list=[form.cleaned_data['email']],
                 fail_silently=False,
             )
            return self.form_valid(form)
        else:
            return self.form_invalid(form)




















# class IndexTableDetailView(DetailView):
#     model = Table
#     template_name = 'group/index.html'
#     context_object_name = 'group'
#
#     def get_object(self, queryset=None):
#         pass
#
#         # id_group = self.kwargs.get(self.pk_url_kwarg)
#         # try:
#         #     group_obj = self.model.objects.get(pk=id_group)
#         # except self.model.DoesNotExist:
#         #     raise Http404("Group does not exist")
#         # return group_obj
#
#     def get(self, request, *args, **kwargs):
#         pass
#
#         # id_group = self.kwargs.get(self.pk_url_kwarg)
#         # if id_group is not None:
#         #     if id_group == 0:
#         #         return HttpResponse("'id' must be greatest when zero")
#
#         return super().get(request, *args, **kwargs)
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(object_list=None, **kwargs)
#         context['title'] = 'Group'
#         return context

src/greek_food/templates/greek_food/base.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {{ title }} {% endblock %}
{% block content %}

{% endblock %}

src/greek_food/templates/greek_food/reserved.html
<div class="form-popup" id="myForm">
  <form method="post" class="form-container">
      {% csrf_token %}
        {{ form }}
      <button type="submit" class="btn btn-success">Create</button>
  </form>
</div>

src/greek_food/templates/greek_food/table_list.html
{% extends 'greek_food/base.html' %}

{% block content %}

<div class="container">
    <div class="row justify-content-center mb-3">
        <div class="col-8">
            <form method="get" class="form-container" >
                <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                    {{ form.date }}
                <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                    <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
                    <button type="submit" class="btn btn-success">Search</button>
                </div>
            </form>
            </div>

    </div>
<script>
  $(function () {
    $("#datetimepicker1").datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
    });
  });
</script>
<div class="row justify-content-center">
    <div class="col-12">
        {% include 'includes/table.html' %}
    </div>
</div>
    </div>

{% endblock %}

src/greek_food/templates/includes/table.html
{% if table_list %}
    <table class="table table-hover">
        <thead class="thead-dark">
            <tr>
              <th>№</th>
              <th>Number</th>
              <th>Number_of_seats</th>
                <th>Is Reserved</th>
                <th></th>
            </tr>
        </thead>
        {% for table in table_list %}
            <tr>
              <td> {{ forloop.counter }} </td>
              <td> {{ table.number }}</td>
              <td> {{ table.number_of_seats }}</td>
                <td>{{ table.is_reserved }}</td>
                <td> <a href="{% url 'greek_food:reserved' table.id %}" class="btn btn-primary">Забронировать</a> </td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <p>Sorry, list is empty</p>
{% endif %}

src/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>


    <title>{% block title %} {{title}} {% endblock %}</title>
</head>
<body>

<div class="container">
    <h2 class="p-3 m-1 bg-light rounded text-center">
        {% block title_page %}{{ title }}{% endblock %}
    </h2>
    <div class="border border-dark rounded p-3 m-3">
        {% block content %}
        {% endblock %}
    </div>
</div>
</body>
</html>